Server:
  port: 8090
  forward-headers-strategy: framework

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: product-read-service
  profiles:
    active: dev

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html